[deps]
hdmf = ">3.6"
wheel = ""
python = ">=3.9,<=3.11"

[pip.deps]
ndx-events = "@https://github.com/rly/ndx-events/archive/refs/tags/0.2.0.zip"
argschema = "@https://github.com/AllenInstitute/argschema/archive/refs/tags/v3.0.1.zip"
allensdk = "@https://github.com/AllenInstitute/AllenSDK/archive/refs/tags/v2.16.2.zip"
