[deps]
pandas = "==1.5.3"
scipy = "<1.11"
numpy = "<1.24"
xarray = "<2023.2.0"
urllib3 = "<2" # Prevents appengine removal error
setuptools = "<81" # Removes warning about pkg_resources deprecation
python = ">=3.9,<3.13"

[pip.deps]
pynwb = "<3"
hdmf = ">3.8,<4"
h5py = "!=3.12.0" # 3.12.0 has windows import issues. Same error for ALL conda versions on windows.
allensdk = "==2.16.2"
argschema = ">=3.0.1"
